AllenInstitute/argschema

json_module/fields.py, json_module/json_module.py, json_module/utils.py, test/test_first_test.py
More compete file validation, fixes some broken validation and implements a few tests.  in case of null inputs, smart_merge now runs with empty dicts rather than returning the other input object.
=> Validation fix

setup.py
the fields submodule doesn't come in the pypi archive
=> missing submodule in setup.py

argschema/argschema_parser.py, argschema/fields/numpyarrays.py, examples/run_template.sh, examples/template_module.py
and i put in a small bug fix in the default run command where json can't dump non-python types
(so i'm just printing the dictionary for now).
I'm particularly interested in whether you think I've handled the numpy data types > marshmallow fields problem in a reasonable fashion.
=> better type handling of numpy array and a better example module 

test/test_first_test.py
added a test for catching bad recursive schemas
=> added a test to demonstrate catching bad recursive schemas

examples/input.json
=> added missing input json file example

argschema/argschema_parser.py, argschema/schemas.py, examples/mymodule.py, examples/template_module.py, test/test_first_test.py
Left out subclassing ArgSchemaParser, not necessary to show it's power, lower barrier to entry.
=> made a simplier first module

README.md
=> gitter badge

README.md
=> fixing gitter badge

argschema/schemas.py, argschema/utils.py, examples/template_module.py, test/fields/test_deprecated.py, test/fields/test_files.py, test/fields/test_numpyarray.py, test/fields/test_slice.py, test/test_first_test.py
I completely removed all references to the less clean description syntax..
=> changed all uses of metadata={'description.. to description

argschema/argschema_parser.py, setup.py, test/test_output.py
This implements output validation as discussed in #38
=> Output validation

examples/template_module.py
change which uses the new output validation feature in the template module, improving documentation as well.
=> changed the way the template module is written to use output validation

argschema/fields/files.py, argschema/utils.py, test/test_utils.py
I've improved testing coverage by adding tests, adding some #pragma: nocover, simplifying the codebase in one place.
=> Improved testing coverage 

.circleci/circle_master_merge.sh
I think this will fix the circleci issue of not merging our dev branch into master that is happening right now because the commit message is missing and circleci can't add a commit message.
=> adding a message so it can merge in if a merge commit is needed

argschema/fields/numpyarrays.py, argschema/fields/slice.py
Slice is technically a string, and this means that the documentation will show its raw type as a string rather than a ?
=> Slice is str

argschema/autodoc.py, test/test_autodoc.py
and overriding python3 FIELD_TYPE_MAP for bytes to write as str.
=> fixing slice tests 

argschema/fields/__init__.py, argschema/fields/files.py, test/fields/test_files.py
added an OutputDir field to complete the set of Files fields
=> added an OutputDir feature

argschema/argschema_parser.py
Jed wanted to have more control over whether to output to output_json in some contexts and do other things in other contexts, so he wanted to get the output_json.
=> broke out getting the output json so it could be independently called

argschema/utils.py, test/test_nested_examples.py
this fixes #68 as we discussed in person, by culling the values which are dictionaries that only contain None as values.
=> Nested non required fix

test/test_utils.py
Reverts AllenInstitute/argschema#71
=> Revert "Test command line string overrides"

.gitignore
small change to add pytest cache to gitignore
=> added pytest_cache

.circleci/config.yml, argschema/fields/files.py, setup.py, test/fields/test_files.py, test_requirements.txt
first test passing on windows. Submitting for checking on automated tests
=> unskip first windows test and mods for passing
