- argschema/fields/__init__.py
It seems helpful to allow fields defined in marshmallow to be accessible within argschema to avoid extra imports and explicit marshmallow dependencies in derived software.
from
```
import argschema
import marshmallow
class MyClass(argschema.ArgSchema):
myint = marshmallow.fields.Int(required=True)
myarr = argschema.fields.NumpyArray(required=True)
```
to
```
import argschema
class MyClass(argschema.ArgSchema):
myint = argschema.fields.Int(required=True)
myarr = argschema.fields.NumpyArray(required=True)
```
> init: allow all marshmallow field types to be accessible from argschema

- argschema/utils.py
I am proposing here that we change to using an ordereddict for building the argparse parser, so that as we go through the schema tree the order that we add the arguments is preserved when we construct the Parser.  This will make the help statements print out in the correct order, rather than the random order they were before.... I think.  Wanted someone to check my thinking.
> changing arguments from dictionary to ordereddict

- argschema/argschema_parser.py
- argschema/schemas.py
- test/test_first_test.py
This addresses #9 backward compatibility in a different way than #8 defining explicit functions to check for recursiveness and for using DefaultSchema. 
argschema.schemas.DefaultSchema should be used to subclass any Schema to be used as a Nested schema within an ArgSchema. 
This PR reverts to the old behavior if the schema contains a non-DefaultSchema schema and is not recursively derived, it also spits out a warning declaring this behavior to be deprecated.  It raises an exception if it contains a non-DefaultSchema schema and is recursively defined (addressing #9).  It bypasses the old functionality if the schema contains no non-DefaultSchema based schemas (as will be the case most of the time with non-Nested Schemas) and defaults will load properly using the pre-load functionality …
> Defaultschema

- .circleci/config.yml
- MANIFEST.in
- requirements.txt
- setup.py
- test/test_first_test.py
- test/test_requirements.txt
- test_requirements.txt
- tox.ini
I have added support for running tests in multiple environments through the use of tox, with tox installed, you should just be able to test all environments with "tox".  Also, I reconfigured the circleci build to do tests of python2.7 and python3.6 using a parallel build workflow.  Forgive me for the excessive number of commits, but when testing CI infrastructure I had to commit many times to test it working correctly.
> multiple environment test support

- Dockerfile.test
wrote this .test dockerfile to install testing requirements for bamboo based workflow, forgot to modify when i moved the test_requirements up a folder.   Passed CircleCi but not bamboo, which is why i missed it.
> fix Dockerfile.test for bamboo based testing

- doc_requirements.txt
- requirements.txt
this removes sphinxcontrib-napoleon from getting installed when building the library.  Will change RTD to read the new requirements file.
> removing sphnix from requirements and adding a test_requirements.txt

- .circleci/config.yml
- .circleci/increment_version.py
- setup.py
I have added a step in circle ci that will auto-increment the most minor version number after it passes tests only on the master branch, this will keep our versions bumping as we successfully merge into master and pass tests.  Next step, auto-publishing to pypi.
> Auto increment circleci

- argschema/autodoc.py
- docs/tests/modules.rst
- docs/tests/test_autodoc.rst
- docs/tests/test_utils.rst
- test/test_autodoc.py
- test_requirements.txt
- tox.ini
I noticed in render-modules that double quotes were not working in descriptions due to the csv-tables way i did things.. i have now replaced them with single quotes in the documentation
> Autodoc refinement

- .circleci/config.yml
This is a simple PR that changes the way the automatic version incremention on circleci works... now the version will be bumped in develop after it passes tests before it is merged with master.  This way develop will always have the most recent version number in its setup.py file, and merge conflicts won't appear when people increment the minor or major version numbers when it seems appropriate, and the CI will increment only the least significant version number.
> Increment version on dev

- argschema/argschema_parser.py
- test/test_output.py
I would like to use this feature to write out multiple output files each of which is validated against the output schema, but to different locations.
> added optional output argument to allow user to specify location 

- argschema/fields/files.py
- test/test_output.py
this makes OutputDir and OutputFile work correctly on nfs mounts, which were having problems.  I don't know how to write a test for this.  I wrote a test that checks that the tmp files were removed after parsing the input, but I don't think that was a problem either except for on NFS mounts.
> Outdir fix

- argschema/fields/__init__.py
- test/test_validate.py
argschema.fields defines __all__, suggesting that `from argschema.fields import *` is supported. This is broken in python 2.7 because marshmallow's __all__ is made up of unicode literals which throws an error for package imports in 2.7. This pull request fixes `from argschema.fields import *` on python 2.7, as well as fixes another issue where appending to __all__ causes any later attempts of `from marshmallow.fields import *` to throw an error.
> Fix star imports

- argschema/argschema_parser.py
- argschema/utils.py
- test/test_argschema_parser.py
- test/test_first_test.py
Jed discovered a problem where he was not getting defaults filled in properly when he didn't pass in something by either input_json/dictionary or command line.  we wrote a test to reproduce the problem and figured out that a small change to test merge will solve the problem.  This also revealed that one of the tests was sort of stupid, with a nested schema which was required, but had a default, but none of its keys were required.  I  made one required to make the tests pass again.
> Fixed nested no defaults

- argschema/utils.py
- test/test_argschema_parser.py
Resolves #64 by using ast.literal_eval to handle the argument in the parser and then letting marshmallow serialization handle the actual type casting.
> Fix boolean command line evaluation

- test/test_utils.py
Opening this PR with just a test that tries to override a string argument with args. Passes in python 2.7 but fails in python 3.6. Probable solution is to exclude bytes from FIELD_TYPE_MAP.
> Test command line string overrides

- argschema/argschema_parser.py
- test/test_argschema_parser.py
A simple QoL change - I like to set the indent parameter when writing json from Python in order to get readable outputs. This change lets the user pass that and other keyword args for json.dump through ArgSchemaParser.output
> allow user to provide json dump options when using ArgSchemaParser.output

- requirements.txt
This will prevent marshmallow 3.0 from being used with argschema, in marshmallow >=3.0.0b7 there is a breaking change in the api that we would need to alter for argschema.
> exclude marshamallow breaking changes

- .appveyor.yml
- setup.cfg
- test/fields/test_files.py
Adds basic appveyor builds for 2.7 and 3.6. Incorporates some test cleanup to prevent tests hanging on Windows. Demonstrates #80 .
> Appveyor tests

- doc_requirements.txt
- docs/conf.py
- docs/user/intro.rst
- examples/mymodule.py
- examples/nested_example.py
- examples/template_module.py
- nested_example.py
Here's some documentation update on the Nested stuff, plus I cleaned up the intro guide to use dynamic outputs of calling things so that what's in the docs will more closely match what output the users will see.
> updated documentation with dynamic output generation and Nested

- argschema/fields/files.py
os.errno exists in python <3.7, but using errno explicitly is better.
> fix errno misuse for python 3.7

- .appveyor.yml
- .circleci/config.yml
- setup.py
- test/test_first_test.py
pytest_runner causes failures when pip installing due to ssl validation. pytest_runner has been deprecated because of this, and it is not used anyways.
> removes setup requires pytest_runner due to pip security and ssl issues

- argschema/fields/files.py
validate_input_path() incurs substantial penalties because it reads the entirety of each input file to verify a file is readable.  The python file class supports the readable() callable for determining readability.
> Changed method of read validation to use the standard library function.  

- README.md
- docs/user/intro.rst
Looks like a few doc files didn't get updated with the name change from ArgSource/Sink to ConfigurableSource/Sink - had me confused for a bit there, this should fix it.
> doc updates for ConfigurableSource/Sink

- argschema/__init__.py
- argschema/autodoc.py
- setup.cfg
* current marshmallow version is 3.12.1. I checked locally and the tests pass at marshmallow 3.0.0
* tweaked one autodoc thing to reproduce the same docstring as before - did not investigate the marshmallow changes that necessitated this deeply.
> bumps marshmallow version and argschema dependency
